name: Python Testing

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    paths:
      - '**.py'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Private Repository
        run: |
          git clone https://x-access-token:${{ secrets.LFS_REPO_ACCESS_TOKEN }}@github.com/cipher982/chatlas_data.git
          mkdir -p ./data/sample/
          mv ./chatlas_data/sample/ ./data/sample/

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run Pytest
        run: |
          ls ./data/sample/
          pytest ./tests/
